name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  test-job:
    name: Testes
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy-job:
    name: Deploy
    runs-on: ubuntu-latest

    needs: test-job  # Garante que o deploy só acontece após os testes serem bem sucedidos

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

