name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  test-job:
    name: Testes
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Run Start
        run: npm start
        
      - name: Run tests
        run: npm test

  deploy-job:
    name: Deploy
    runs-on: ubuntu-latest

    needs: test-job  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

