name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  test-job:
    name: Tests
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          
      - name: run install and tests
        run:
          npm install
          npm run build
          npm run test

  deploy-job:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test-job  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        run: echo "Finalizado"
