name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  test-job:
    name: Tests
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test

  deploy-job:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test-job

    steps:
      - name: Checkout
        run: echo "Finalizado"

      - name: Notify on Discord
        uses: appleboy/telegram-action@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "Nova versão da aplicação disponível!"



